name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout repo
      - name: Set up Python 3.10
          uses: actions/setup-python@v2
          with:
            python-version: "3.10"
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install coverage
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi- name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          ls
          python -m pip install --upgrade pip
          pip install coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Coverage Test
        run: |
          echo "Unit test"
          coverage run -m unittest discover
          coverage xml -o coverage2.xml
          ls
      - name: Upload Coverage report to Sonar Job
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage2.xml

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: ["unit-test"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download Coverage report from Build Job
        uses: actions/download-artifact@v3
        with:
          name: coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master